### ISSUE TITLE
Stats page appears to be static

### ISSUE THREAD

**Issue by dennislwm** [uppernauts/year-in-dev#4]
Even after a new article was published in Dev.to, my stats page doesn't appear to update from Dev.to. The page appears to be a static page.

**Comment by pawap90** [comment]
Hi! Thanks for reporting this issue. 
We're looking into it and it appears related to DEV's API cache since even when we execute the request from Postman it still doesn't return the latest results. I'll keep you posted.

**Comment by mauro-codes** [comment]
@dennislwm Thanks again for reporting this issue! Now it's fixed and online so you can check your updated stats.
